function love.conf(t)
    t.title = "Your Game Title"            -- The title of the window the game is in (string)
    t.author = "Your Name"                 -- The author of the game (string)
    t.window.width = 1400                  -- The window width (number)
    t.window.height = 800                -- The window height (number)
    t.console = false                      -- Attach a console (boolean, Windows only)
    t.window.fullscreen = false            -- Enable fullscreen (boolean)
    t.window.vsync = true                  -- Enable vertical sync (boolean)
    t.window.msaa = 0                      -- The number of samples to use with multi-sampled antialiasing (number)
    t.modules.audio = true                 -- Enable the audio module (boolean)
    t.modules.keyboard = true              -- Enable the keyboard module (boolean)
    t.modules.event = true                 -- Enable the event module (boolean)
    t.modules.image = true                 -- Enable the image module (boolean)
    t.modules.graphics = true              -- Enable the graphics module (boolean)
    t.modules.timer = true                 -- Enable the timer module (boolean)
    t.modules.mouse = true                 -- Enable the mouse module (boolean)
    t.modules.sound = true                 -- Enable the sound module (boolean)
    t.modules.physics = true               -- Enable the physics module (boolean)
    t.modules.window = true                -- Enable the window module (boolean)
    t.modules.thread = true                -- Enable the thread module (boolean)
end